# Generated by Django 5.2 on 2025-05-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_survey', models.DateField()),
                ('liked_most', models.CharField(max_length=255)),
                ('source_of_interest', models.CharField(max_length=50)),
                ('recommend', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
