# Generated by Django 5.2 on 2025-05-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='survey',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='liked_most',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='survey',
            name='recommend',
            field=models.CharField(choices=[('very_likely', 'Very Likely'), ('likely', 'Likely'), ('unlikely', 'Unlikely')], max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='source_of_interest',
            field=models.CharField(choices=[('friends', 'Friends'), ('tv', 'Television'), ('internet', 'Internet'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
